SMS_KEY = 'YOUR API FROM WEB-SITE' # https://sms-activate.ru/ <---- only working with this site
DEFAULT_PASSWORD = 'YOUR ACCOUNTS DEFAULT PASSWORD' # example: iLovePython
DEFAULT_ADDRESS = 'ACCOUNT LIVING ADDRES'
DEFAULT_CITY = 'ACCOUNT CITY'
DEFAULT_REGION = 'ACCOUNT REGION'
DEFAULT_ZIP = 'REGION ZIPCODE'
